feat: WIP: New slide ETL
msk-mind/luna pull request #271
Opened 2022-01-25 22:55 UTC by aauker

2022-01-31 16:31 UTC, doori commented on pyluna-pathology/luna/pathology/cli/slide_etl.py
> +            write_kv = self.writer.write(path, f'{self.project}/slides')
Recommend separating extracting openslide kv pairs / writing slide in 2 separate methods.

2022-01-31 16:35 UTC, doori requested changes
Great reusable IOAdapter that handles writing to minio / local storage.

Suggest to make the write step optional for slides that don't need to be moved around.

Remove `tests/luna/pathology/proxy_table/chunks.txt` `tests/luna/pathology/proxy_table/data.yaml` were used by test_generate.py

2022-01-31 16:45 UTC, doori commented on pyluna-pathology/luna/pathology/cli/slide_etl.py
> +    logger.info(slide_paths)
It would be great to optionally pass in a csv/txt file to subset what we ETL from the slide_paths.

2022-02-01 16:52 UTC, aauker commented
See: https://mskcc.box.com/s/uj916g18fdfe46lmht6zg6ksgqmdjthj for examples (including subsetting)

2022-02-01 17:10 UTC, doori approved these changes
👍

2022-02-01 17:22 UTC, merged

2022-02-03 15:18 UTC, arfathpasha reviewed
comments made for DDD design discussion